# Generated by Django 5.0.7 on 2024-07-14 13:23

import builtins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gpsTollApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='gpstollapptrip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip_id', models.IntegerField(unique=True)),
                ('source', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('no_tollscrossed', models.CharField(max_length=100)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_status', models.CharField(max_length=50)),
                ('trip_date', models.DateField(max_length=25)),
                ('vehicle_regno', models.CharField(max_length=50)),
                ('Applicant_name', models.CharField(max_length=100)),
                ('vehicle_catid', models.IntegerField()),
                ('validity_from', models.DateField(max_length=25)),
                ('validity_to', models.DateField(max_length=25)),
                ('costof_pass', models.DecimalField(decimal_places=2, max_digits=22)),
                ('Vehicle_name', models.CharField(max_length=100)),
                ('distance', models.DecimalField(decimal_places=2, max_digits=22)),
            ],
        ),
        migrations.CreateModel(
            name='vehiclecategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_id', models.IntegerField(unique=True)),
                ('vehicle_type', models.CharField(max_length=100)),
                ('toll_amount', models.DecimalField(decimal_places=2, max_digits=22)),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='Address',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='dateofbirth',
            field=models.DateField(default='', max_length=builtins.any),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='super_user',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='email',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='last_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='password',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='sex',
            field=models.CharField(default='', max_length=10),
        ),
    ]
