# Generated by Django 5.0.7 on 2024-07-14 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gpsTollApp', '0003_remove_userprofile_dateofbirth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='super_user',
            field=models.BooleanField(default=False),
        ),
    ]
