# Generated by Django 5.0.7 on 2024-07-14 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gpsTollApp', '0005_userprofile1_delete_userprofile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserProfile1',
            new_name='UserProfile',
        ),
    ]
