# Generated by Django 5.0.7 on 2024-07-14 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gpsTollApp', '0006_rename_userprofile1_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='userid',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
